# Generated by Django 5.0.6 on 2026-06-28 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(max_length=80)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('historical', 'Historical'), ('nature', 'Nature & Wildlife'), ('adventure', 'Adventure'), ('cultural', 'Cultural')], default='city', max_length=20)),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of descriptive tags')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('average_cost_per_day_usd', models.PositiveIntegerField(default=0)),
                ('best_season', models.CharField(blank=True, default='', max_length=60)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('destination', 'author')},
            },
        ),
    ]
