# Generated by Django 5.0.6 on 2026-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='embedding_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_attribution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='wikipedia_title',
            field=models.CharField(blank=True, default='', help_text='Wikipedia article title, used to fetch a real photo and credit it.', max_length=160),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category'], name='destination_categor_7c9900_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='destination_country_2ade19_idx'),
        ),
    ]
